var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/estate_developer/kasturi/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3d991c7c._.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_ed33c703._.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_d0817613._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c26549c._.js")
R.c("server/chunks/ssr/f6976_next_dist_988c6743._.js")
R.c("server/chunks/ssr/f6976_next_dist_13fdf149._.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_app_2521e014._.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_builtin_global-error_ed162cb5.js")
R.c("server/chunks/ssr/[root-of-the-server]__9d703f70._.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_c289b28f._.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_builtin_forbidden_84144b3f.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_builtin_unauthorized_edd3f7c6.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_app_estate_developer_layout_tsx_7848b5cd._.js")
R.c("server/chunks/ssr/325f6_fe__next-internal_server_app_estate_developer_kasturi_page_actions_af5d88ae.js")
R.m(88664)
module.exports=R.m(88664).exports
