// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about-us-real-estate-agency" | "/about-us-real-estate-agency/bhavik1" | "/blog" | "/blog/[slug]" | "/career" | "/career/[jobTitle]" | "/contact-us-propertydrone-realty" | "/dashboard" | "/dashboard/add-plots" | "/dashboard/addblog" | "/dashboard/addexpert" | "/dashboard/addnews" | "/dashboard/addreal" | "/dashboard/allblogs" | "/dashboard/allnews" | "/dashboard/allreal" | "/dashboard/applications" | "/dashboard/applicationsform" | "/dashboard/careerform" | "/dashboard/careers" | "/dashboard/contactdetail" | "/dashboard/contactform" | "/dashboard/cookie-consents" | "/dashboard/experts" | "/dashboard/projectdetail" | "/dashboard/projectform" | "/dashboard/propertycomparison" | "/dashboard/propertydetail" | "/dashboard/propertyform" | "/dashboard/savedproperty" | "/dashboard/showallplots" | "/dashboard/testimonials" | "/dashboard/user-properties" | "/dashboard/webusers" | "/dashboard/youtube" | "/dashboard/youtube/new" | "/emi-calculator" | "/estate_developer" | "/estate_developer/Solitaire" | "/estate_developer/anp-corp" | "/estate_developer/kasturi" | "/estate_developer/krunal-group" | "/estate_developer/majestique-developer" | "/estate_developer/skyi-developers" | "/irr-calculator" | "/login" | "/lrd-calculator" | "/luxe-properties" | "/luxe-properties/[slug]" | "/news" | "/news/[slug]" | "/nri-corner" | "/our-properties-in-pune" | "/our-properties-in-pune/[slug]" | "/our-services-real-estate-services" | "/post-property" | "/privacy-policy" | "/profile" | "/real_estate_basic" | "/real_estate_basic/[id]" | "/register" | "/roi-calculator" | "/saved-properties" | "/signin" | "/signup" | "/terms-and-condition" | "/thank-you" | "/weblogin" | "/webregister"
type AppRouteHandlerRoutes = "/api/youtube-videos"
type PageRoutes = never
type LayoutRoutes = "/" | "/about-us-real-estate-agency" | "/blog" | "/compareproperties" | "/components" | "/contact-us-propertydrone-realty" | "/dashboard" | "/estate_developer" | "/luxe-properties" | "/nri-corner" | "/our-services-real-estate-services"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about-us-real-estate-agency": {}
  "/about-us-real-estate-agency/bhavik1": {}
  "/api/youtube-videos": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/career": {}
  "/career/[jobTitle]": { "jobTitle": string; }
  "/compareproperties": {}
  "/components": {}
  "/contact-us-propertydrone-realty": {}
  "/dashboard": {}
  "/dashboard/add-plots": {}
  "/dashboard/addblog": {}
  "/dashboard/addexpert": {}
  "/dashboard/addnews": {}
  "/dashboard/addreal": {}
  "/dashboard/allblogs": {}
  "/dashboard/allnews": {}
  "/dashboard/allreal": {}
  "/dashboard/applications": {}
  "/dashboard/applicationsform": {}
  "/dashboard/careerform": {}
  "/dashboard/careers": {}
  "/dashboard/contactdetail": {}
  "/dashboard/contactform": {}
  "/dashboard/cookie-consents": {}
  "/dashboard/experts": {}
  "/dashboard/projectdetail": {}
  "/dashboard/projectform": {}
  "/dashboard/propertycomparison": {}
  "/dashboard/propertydetail": {}
  "/dashboard/propertyform": {}
  "/dashboard/savedproperty": {}
  "/dashboard/showallplots": {}
  "/dashboard/testimonials": {}
  "/dashboard/user-properties": {}
  "/dashboard/webusers": {}
  "/dashboard/youtube": {}
  "/dashboard/youtube/new": {}
  "/emi-calculator": {}
  "/estate_developer": {}
  "/estate_developer/anp-corp": {}
  "/estate_developer/kasturi": {}
  "/estate_developer/krunal-group": {}
  "/estate_developer/majestique-developer": {}
  "/estate_developer/skyi-developers": {}
  "/estate_developer/Solitaire": {}
  "/irr-calculator": {}
  "/login": {}
  "/lrd-calculator": {}
  "/luxe-properties": {}
  "/luxe-properties/[slug]": { "slug": string; }
  "/news": {}
  "/news/[slug]": { "slug": string; }
  "/nri-corner": {}
  "/our-properties-in-pune": {}
  "/our-properties-in-pune/[slug]": { "slug": string; }
  "/our-services-real-estate-services": {}
  "/post-property": {}
  "/privacy-policy": {}
  "/profile": {}
  "/real_estate_basic": {}
  "/real_estate_basic/[id]": { "id": string; }
  "/register": {}
  "/roi-calculator": {}
  "/saved-properties": {}
  "/signin": {}
  "/signup": {}
  "/terms-and-condition": {}
  "/thank-you": {}
  "/weblogin": {}
  "/webregister": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/about-us-real-estate-agency": never
  "/blog": never
  "/compareproperties": never
  "/components": never
  "/contact-us-propertydrone-realty": never
  "/dashboard": never
  "/estate_developer": never
  "/luxe-properties": never
  "/nri-corner": never
  "/our-services-real-estate-services": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
