// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/about-us-real-estate-agency/bhavik1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-us-real-estate-agency/bhavik1">> = Specific
  const handler = {} as typeof import("../../app/about-us-real-estate-agency/bhavik1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/about-us-real-estate-agency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about-us-real-estate-agency">> = Specific
  const handler = {} as typeof import("../../app/about-us-real-estate-agency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/career/[jobTitle]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/career/[jobTitle]">> = Specific
  const handler = {} as typeof import("../../app/career/[jobTitle]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/career/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/career">> = Specific
  const handler = {} as typeof import("../../app/career/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact-us-propertydrone-realty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact-us-propertydrone-realty">> = Specific
  const handler = {} as typeof import("../../app/contact-us-propertydrone-realty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/addblog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/addblog">> = Specific
  const handler = {} as typeof import("../../app/dashboard/addblog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/addexpert/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/addexpert">> = Specific
  const handler = {} as typeof import("../../app/dashboard/addexpert/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/addnews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/addnews">> = Specific
  const handler = {} as typeof import("../../app/dashboard/addnews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/addreal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/addreal">> = Specific
  const handler = {} as typeof import("../../app/dashboard/addreal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/allblogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/allblogs">> = Specific
  const handler = {} as typeof import("../../app/dashboard/allblogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/allnews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/allnews">> = Specific
  const handler = {} as typeof import("../../app/dashboard/allnews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/allreal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/allreal">> = Specific
  const handler = {} as typeof import("../../app/dashboard/allreal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applications">> = Specific
  const handler = {} as typeof import("../../app/dashboard/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/applicationsform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/applicationsform">> = Specific
  const handler = {} as typeof import("../../app/dashboard/applicationsform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/careerform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/careerform">> = Specific
  const handler = {} as typeof import("../../app/dashboard/careerform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/careers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/careers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/careers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/contactdetail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/contactdetail">> = Specific
  const handler = {} as typeof import("../../app/dashboard/contactdetail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/contactform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/contactform">> = Specific
  const handler = {} as typeof import("../../app/dashboard/contactform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/cookie-consents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cookie-consents">> = Specific
  const handler = {} as typeof import("../../app/dashboard/cookie-consents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/experts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/experts">> = Specific
  const handler = {} as typeof import("../../app/dashboard/experts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/projectdetail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/projectdetail">> = Specific
  const handler = {} as typeof import("../../app/dashboard/projectdetail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/projectform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/projectform">> = Specific
  const handler = {} as typeof import("../../app/dashboard/projectform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/propertycomparison/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/propertycomparison">> = Specific
  const handler = {} as typeof import("../../app/dashboard/propertycomparison/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/propertydetail/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/propertydetail">> = Specific
  const handler = {} as typeof import("../../app/dashboard/propertydetail/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/propertyform/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/propertyform">> = Specific
  const handler = {} as typeof import("../../app/dashboard/propertyform/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/savedproperty/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/savedproperty">> = Specific
  const handler = {} as typeof import("../../app/dashboard/savedproperty/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/testimonials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/testimonials">> = Specific
  const handler = {} as typeof import("../../app/dashboard/testimonials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/user-properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/user-properties">> = Specific
  const handler = {} as typeof import("../../app/dashboard/user-properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/webusers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/webusers">> = Specific
  const handler = {} as typeof import("../../app/dashboard/webusers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/youtube/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/youtube/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/youtube/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/youtube/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/youtube">> = Specific
  const handler = {} as typeof import("../../app/dashboard/youtube/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/emi-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/emi-calculator">> = Specific
  const handler = {} as typeof import("../../app/emi-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/estate_developer/Solitaire/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estate_developer/Solitaire">> = Specific
  const handler = {} as typeof import("../../app/estate_developer/Solitaire/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/estate_developer/anp-corp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estate_developer/anp-corp">> = Specific
  const handler = {} as typeof import("../../app/estate_developer/anp-corp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/estate_developer/kasturi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estate_developer/kasturi">> = Specific
  const handler = {} as typeof import("../../app/estate_developer/kasturi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/estate_developer/krunal-group/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estate_developer/krunal-group">> = Specific
  const handler = {} as typeof import("../../app/estate_developer/krunal-group/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/estate_developer/majestique-developer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estate_developer/majestique-developer">> = Specific
  const handler = {} as typeof import("../../app/estate_developer/majestique-developer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/estate_developer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estate_developer">> = Specific
  const handler = {} as typeof import("../../app/estate_developer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/estate_developer/skyi-developers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/estate_developer/skyi-developers">> = Specific
  const handler = {} as typeof import("../../app/estate_developer/skyi-developers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/irr-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/irr-calculator">> = Specific
  const handler = {} as typeof import("../../app/irr-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lrd-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lrd-calculator">> = Specific
  const handler = {} as typeof import("../../app/lrd-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/luxe-properties/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/luxe-properties/[slug]">> = Specific
  const handler = {} as typeof import("../../app/luxe-properties/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/luxe-properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/luxe-properties">> = Specific
  const handler = {} as typeof import("../../app/luxe-properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/news/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news/[slug]">> = Specific
  const handler = {} as typeof import("../../app/news/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/news/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/news">> = Specific
  const handler = {} as typeof import("../../app/news/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/nri-corner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nri-corner">> = Specific
  const handler = {} as typeof import("../../app/nri-corner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/our-properties-in-pune/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/our-properties-in-pune/[slug]">> = Specific
  const handler = {} as typeof import("../../app/our-properties-in-pune/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/our-properties-in-pune/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/our-properties-in-pune">> = Specific
  const handler = {} as typeof import("../../app/our-properties-in-pune/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/our-services-real-estate-services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/our-services-real-estate-services">> = Specific
  const handler = {} as typeof import("../../app/our-services-real-estate-services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/post-property/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/post-property">> = Specific
  const handler = {} as typeof import("../../app/post-property/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/real_estate_basic/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/real_estate_basic/[id]">> = Specific
  const handler = {} as typeof import("../../app/real_estate_basic/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/real_estate_basic/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/real_estate_basic">> = Specific
  const handler = {} as typeof import("../../app/real_estate_basic/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/roi-calculator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roi-calculator">> = Specific
  const handler = {} as typeof import("../../app/roi-calculator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/saved-properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saved-properties">> = Specific
  const handler = {} as typeof import("../../app/saved-properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signin">> = Specific
  const handler = {} as typeof import("../../app/signin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms-and-condition/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-and-condition">> = Specific
  const handler = {} as typeof import("../../app/terms-and-condition/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/thank-you/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/thank-you">> = Specific
  const handler = {} as typeof import("../../app/thank-you/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/weblogin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/weblogin">> = Specific
  const handler = {} as typeof import("../../app/weblogin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/webregister/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/webregister">> = Specific
  const handler = {} as typeof import("../../app/webregister/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/about-us-real-estate-agency/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/about-us-real-estate-agency">> = Specific
  const handler = {} as typeof import("../../app/about-us-real-estate-agency/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compareproperties/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/compareproperties">> = Specific
  const handler = {} as typeof import("../../app/compareproperties/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/components/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/components">> = Specific
  const handler = {} as typeof import("../../app/components/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact-us-propertydrone-realty/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact-us-propertydrone-realty">> = Specific
  const handler = {} as typeof import("../../app/contact-us-propertydrone-realty/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/estate_developer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/estate_developer">> = Specific
  const handler = {} as typeof import("../../app/estate_developer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/luxe-properties/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/luxe-properties">> = Specific
  const handler = {} as typeof import("../../app/luxe-properties/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/nri-corner/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/nri-corner">> = Specific
  const handler = {} as typeof import("../../app/nri-corner/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/our-services-real-estate-services/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/our-services-real-estate-services">> = Specific
  const handler = {} as typeof import("../../app/our-services-real-estate-services/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
