var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/propertycomparison/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3f974e92._.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_ed33c703._.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_730735b3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c26549c._.js")
R.c("server/chunks/ssr/f6976_next_dist_988c6743._.js")
R.c("server/chunks/ssr/f6976_next_dist_13fdf149._.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_app_2521e014._.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_builtin_global-error_ed162cb5.js")
R.c("server/chunks/ssr/[root-of-the-server]__9d703f70._.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_c289b28f._.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_builtin_forbidden_84144b3f.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_builtin_unauthorized_edd3f7c6.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_app_dashboard_layout_503321fb.js")
R.c("server/chunks/ssr/325f6_fe__next-internal_server_app_dashboard_propertycomparison_page_actions_6d47739d.js")
R.m(86726)
module.exports=R.m(86726).exports
