var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/about-us-real-estate-agency/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b8d158d._.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_ed33c703._.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_a2a321af._.js")
R.c("server/chunks/ssr/[root-of-the-server]__4c26549c._.js")
R.c("server/chunks/ssr/f6976_next_dist_988c6743._.js")
R.c("server/chunks/ssr/f6976_next_dist_13fdf149._.js")
R.c("server/chunks/ssr/propertydrone_propertydrone_fe_app_2521e014._.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_builtin_global-error_ed162cb5.js")
R.c("server/chunks/ssr/[root-of-the-server]__9d703f70._.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_c289b28f._.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_builtin_forbidden_84144b3f.js")
R.c("server/chunks/ssr/f6976_next_dist_client_components_builtin_unauthorized_edd3f7c6.js")
R.c("server/chunks/ssr/f0044_propertydrone_fe_app_about-us-real-estate-agency_layout_tsx_7ab13fae._.js")
R.c("server/chunks/ssr/325f6_fe__next-internal_server_app_about-us-real-estate-agency_page_actions_bcc264f2.js")
R.m(33810)
module.exports=R.m(33810).exports
